# Setting Up

In [1]:
import torch
import numpy as np
import pandas as pd
print("CUDA available:", torch.cuda.is_available())

CUDA available: True


In [2]:
!nvidia-smi

Thu Jul 23 18:48:37 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 610.74                 KMD Version: 610.74        CUDA UMD Version: 13.3     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4080 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   45C    P0             27W /  160W |       0MiB /  12282MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

# Initializing Tensors

## Defining Tensors

### Scalers

In [3]:
scaler = torch.tensor(3.0)
scaler

tensor(3.)

#### Dimensions

In [4]:
scaler.ndim

0

#### Shape

In [5]:
scaler.shape

torch.Size([])

#### Ndim == len(Shape) 

In [6]:
scaler.ndim == len(scaler.shape)

True

### Vectors

In [7]:
vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

#### Dimensions

In [8]:
vector.ndim


1

#### Shape

In [9]:
vector.shape

torch.Size([3])

#### Vectors can consist of a single scaler

In [10]:
vector = torch.tensor([1])
vector

tensor([1])

### Matrics (2 dimensional only)

In [11]:
MATRIX = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

#### Dimensions

In [12]:
MATRIX.ndim


2

#### Shape

In [13]:
MATRIX.shape

torch.Size([2, 3])

### Tensors (n-dimensional)

In [14]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                        
                        [[10, 11, 12],
                        [13, 14, 15],
                        [16, 17, 18]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

#### Dimensions

In [15]:
TENSOR.ndim


3

#### Shape

In [16]:
TENSOR.shape

torch.Size([2, 3, 3])

### Notes

- ##### We capitalize tensors and matrics while lower casing vectors and scalers, that is why W and X are always uppercase, while y and b (if alone) are always lowercase.

- ##### Matrices and Tensors are used interchangably, since we are always initializing by .Tensor but what is inside dictates whether it is or not

### .tensor() creates a copy of the data

In [17]:
array = np.array([1, 2, 3])
tensor = torch.tensor(array)

In [18]:
tensor[0] = 999
print("Numpy array:", array)
print("Torch tensor:", tensor)


Numpy array: [1 2 3]
Torch tensor: tensor([999,   2,   3])


#### To avoid that, we can use torch.as_tensor() to convert np array to tensor

In [19]:
array = np.array([1, 2, 3])
tensor = torch.as_tensor(array)

In [20]:
tensor[0] = 999
print("Numpy array:", array)
print("Torch tensor:", tensor)


Numpy array: [999   2   3]
Torch tensor: tensor([999,   2,   3])


## Random Tensors

### Rand()

##### rand() gives a uniform distribution [0,1)
##### this can be used for Probabilities, dropout mask, or exploration noise

In [21]:
random = torch.rand(3)
random

tensor([0.6704, 0.7526, 0.0609])

- ##### size of the tensor is always needed
- ##### by default, the type is float32

In [22]:
random.dtype

torch.float32

In [23]:
torch.rand(size=(3, 4), dtype=torch.float16)

tensor([[0.6748, 0.0226, 0.5137, 0.5630],
        [0.0075, 0.4619, 0.3740, 0.5972],
        [0.6646, 0.8252, 0.3020, 0.0751]], dtype=torch.float16)

### Randn()

#### randn gives a normal distribution (mean of 0 and std of 1) (-inf,+inf)
#### This is what we will mostly use for RL, and DL in general

In [24]:
random = torch.randn([3,255,255])
random


tensor([[[ 0.3384,  0.8164, -1.6632,  ..., -0.9723,  0.0700, -0.4169],
         [-1.4038,  0.7101,  1.0272,  ..., -0.2885,  0.3677, -2.0933],
         [ 0.0365, -1.7548,  0.4018,  ...,  1.4679, -0.1917,  2.0616],
         ...,
         [ 1.0029,  0.2968,  1.5055,  ..., -0.4268, -0.5148,  0.7274],
         [ 0.5784,  1.1165,  0.0654,  ..., -0.3022, -0.0897,  0.3109],
         [-1.0180,  1.4485,  0.3628,  ...,  0.2507, -1.1899,  0.4342]],

        [[-0.6939,  0.2274,  1.3455,  ...,  0.1897, -0.0958,  0.4784],
         [-0.6586, -1.5437,  1.1827,  ...,  1.5056, -0.2321,  0.6681],
         [-0.0418,  0.0794,  0.7341,  ...,  1.5645, -0.6755, -1.7412],
         ...,
         [ 1.1367, -0.5644,  0.1215,  ...,  0.0858, -1.3755,  1.0610],
         [-1.1817,  0.4147, -0.8828,  ...,  0.2679,  0.2264,  1.0626],
         [-1.2178,  1.0426, -0.3908,  ...,  1.4902, -1.8647, -0.5225]],

        [[-0.1681,  0.0595, -0.9553,  ...,  0.6110,  0.7490, -0.0965],
         [ 0.8277, -0.0391,  1.1202,  ..., -2

### Randint()

#### Discrete Uniform Integers [low,high)
#### Sampling random batch indices, discrete action spaces

In [25]:
# High and low parameters are required
torch.randint(size=(3, 4),high=10, low=0)

tensor([[6, 5, 7, 3],
        [1, 5, 1, 2],
        [8, 6, 9, 8]])

### Random state in pytorch

In [26]:
# Global seed
torch.manual_seed(42)
W=torch.rand(3, 4)
W

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [27]:
g =  torch.Generator().manual_seed(43)
W = torch.rand(3, 4, generator=g)
W

tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])

In [28]:
W.ndim,W.shape

(2, torch.Size([3, 4]))

## Zeros and Ones Tensor

### Zeros Tensor

In [29]:
Z=torch.zeros(size=(3, 4), dtype=torch.float16)
Z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float16)

### Ones Tensor

In [30]:
O=torch.ones(size=(3, 4))
O,O.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Devices

In [31]:
print(torch.cuda.is_available())        # Returns True if CUDA GPU is ready
print(torch.cuda.device_count())        # Number of available GPUs
print(torch.cuda.get_device_name(0))

True
1
NVIDIA GeForce RTX 4080 Laptop GPU


In [32]:
device = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"
device

'cuda'

### Default initilizations use CPU, to transfer to GPU use this

In [33]:
# BAD: Allocates on CPU, then copies memory to GPU
x = torch.rand(3, 4)
# Not in place, you need to assign it back to x or another variable (only for tensors, not for modules)
x = x.to(device)
x

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]], device='cuda:0')

In [34]:
# GOOD: Allocates directly in GPU memory
x = torch.rand(3, 4, device=device)
x

tensor([[0.6130, 0.0101, 0.3984, 0.0403],
        [0.1563, 0.4825, 0.7362, 0.4060],
        [0.5189, 0.2867, 0.2416, 0.9228]], device='cuda:0')

### Operations Require Same Device Tensor

In [35]:
a = torch.ones(2, 2, device="cpu")
b = torch.ones(2, 2, device="cuda")

# CRASH! Raises RuntimeError
# c = a + b 

# FIX: Bring 'a' to 'cuda' first
c = a.to("cuda") + b

### Back To Numpy

In [36]:
x = torch.randn(3, 3, device="cuda")

# BAD: Raises RuntimeError (GPU memory + autograd attached)
# np_arr = x.numpy()

# GOOD: Detaches graph, copies to CPU memory, then converts to NumPy
np_arr = x.cpu().numpy()
np_arr

array([[ 0.13913755, -0.10821664, -0.71742225],
       [ 0.7566486 ,  0.37148806, -1.0049413 ],
       [ 0.00829473,  0.3276579 ,  0.28290802]], dtype=float32)

## Like functions

#### There are like functions that create a tensor with all the attributes such as device or shape of the passed tensor

In [37]:
state = torch.tensor([1.5, 2.0], device="cuda", dtype=torch.float32)
# Not the best way and prone to errors if you forget the device or dtype
noise = torch.rand(state.shape, device=state.device, dtype=state.dtype)
# Better Approach
noise = torch.rand_like(state)