# Setting Up

In [1]:
import torch
import numpy as np
import pandas as pd
print("CUDA available:", torch.cuda.is_available())

CUDA available: True


In [2]:
!nvidia-smi

Thu Jul 23 18:54:00 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 610.74                 KMD Version: 610.74        CUDA UMD Version: 13.3     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4080 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   40C    P8              1W /  160W |     198MiB /  12282MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

# Manipulating Tensors

## 1. Basic Operations

### Tensor with Scaler

#### Addition

In [3]:
T = torch.tensor([1,2,3])
T + 10

tensor([11, 12, 13])

In [9]:
torch.add(T, 10) #not in-place

tensor([11, 12, 13])

#### Multiplication

In [10]:
T*10

tensor([10, 20, 30])

In [11]:
torch.multiply(T, 10) #not in-place

tensor([10, 20, 30])

#### Division

In [5]:
T/10

tensor([0.1000, 0.2000, 0.3000])

In [13]:
torch.divide(T, 10) #not in-place

tensor([0.1000, 0.2000, 0.3000])

#### Subtraction

In [6]:
T-10

tensor([-9, -8, -7])

In [12]:
torch.subtract(T, 10) #not in-place

tensor([-9, -8, -7])

### Tensor with Tensor

#### Addition

##### To add tensors together, they have to be either:

- ##### Same shape (all dimensions are the same)

In [15]:
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[4,5,6],[7,8,9]])
a + b

tensor([[ 5,  7,  9],
        [11, 13, 15]])

- ##### When they are not equal in a certain dimension, one of the dimensions is equal to one (broadcasting)

In [20]:
a = torch.tensor([[[1,2,3],[10,11,12]]])
print(a.shape)

b= torch.tensor([[[4,5,6]],[[7,8,9]]])
print(b.shape)

a+b

torch.Size([1, 2, 3])
torch.Size([2, 1, 3])


tensor([[[ 5,  7,  9],
         [14, 16, 18]],

        [[ 8, 10, 12],
         [17, 19, 21]]])

- ##### One tesnor has fewer dimensions (this is what makes the tensor+scaler work)

In [24]:
a = torch.tensor([[1,2,3],[10,11,12]])
print(a.shape)
b = torch.tensor([4,5,6])
print(b.shape)

a+b

torch.Size([2, 3])
torch.Size([3])


tensor([[ 5,  7,  9],
        [14, 16, 18]])

#### Multiplication

## 2. Shape-Shifting

## 3. Combining & Splitting

## 4. Slicing & Indexing

## 5. Aggregation